#!/usr/bin/env bash

#
# View the top file that eats the most space
# should be run as a sudoer or a root
#

#
# HOWTO
#
# `top-disk-usage`
# Will list the 10 top most consuming elements in the curdir
#
# `top-disk-usage <where>`
# Will list the 10 top most consuming elements in <where>
#
# `top-disk-usage <where> <number>`
# Will list the <number> top most consuming elements in <where>
#

target=$1
number=$2
curdir=`pwd`

if [ -z "$target" ]; then
    target=$curdir
fi

if [ -z "$number" ]; then
    number=10
fi

echo "Here are the top $number files / directories in $target :"

cd $target
du -hsx | sort -rh | head -n "$number"
cd $curdir

